### PR TITLE
gcassert: allow absolute paths to be used for packages, and add cwd arg

### PR DESCRIPTION
**Pull request by rickystewart**

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]

**Comment by yuzefovich** [comment]
@rickystewart looks like the build failed

**Comment by jordanlewis** [comment]
Looks reasonable, though I don't love that it breaks the API for current users. How about a CWD-passing variant? Also, could you please add an absolute path test and an explicit CWD test?

**Comment by rickystewart** [comment]
@jordanlewis Have a look. Also fixed the test.

**Review by jordanlewis — APPROVED** [review]
LGTM. thank you!

**Pull request merged**
